version: "3"
services:
  kakao-noti-server:
    container_name: nestjs-example
    build:
      context: ./
      dockerfile: ./Dockerfile
    platform: linux/amd64
    image: nestjs-example
    restart: always
    ports:
      - 3000:3000
    stdin_open: true # docker run -i
    tty: true # docker run -t
    environment:
      TZ: Asia/Seoul
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: yarn start:dev
