version: '3'
services:
  nestjs-template-local:
    container_name: nestjs-graphql-prisma-template-local
    build:
      context: ./
      dockerfile: ./Dockerfile.local
    platform: linux/amd64
    restart: always
    ports:
      - 3000:3000
    stdin_open: true # docker run -i
    tty: true # docker run -t
    environment:
      TZ: Asia/Seoul
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: yarn start:dev
