# appspec.yml의 이름을 수정하려면 CodeDeploy Agent 1.3.2 이상이 필요합니다.
# EC2에서 codedeploy-local -A [FileName] 명령을 사용하면 됩니다.
version: 0.0
os: linux
# EC2 배포에서만 files 옵션을 사용할 수 있습니다.
files:
  # buildArtifact에서 아래 소스만 복사합니다.
  - source: /docker-compose.dev.yml
    # 해당 경로로 파일이 복사됩니다.
    destination: /opt/docker/[REPO]/dev
hooks:
  ApplicationStop:
    - location: timestamp.sh
  BeforeInstall:
    # deploy.sh에서 사용할 환경변수를 설정합니다.
    - location: env-load.sh
  AfterInstall:
    - location: deploy.sh
  ApplicationStart:
    - location: timestamp.sh
  ValidateService:
    - location: local-docker-gc.sh
